/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import dragDropContentTypes from "@retikolo/drag-drop-content-types/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import autoAltCaptionTitleOnImagesAiEnhanced from "strapi-plugin-auto-alt-caption-title-on-images-ai-enhanced/strapi-admin";
import translate from "strapi-plugin-translate/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "drag-drop-content-types": dragDropContentTypes,
    documentation: documentation,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "auto-alt-caption-title-on-images-ai-enhanced":
      autoAltCaptionTitleOnImagesAiEnhanced,
    translate: translate,
  },
});
