name: Just Build Docker

on:
  pull_request:
    branches: ["main"]

env:
  JWT_SECRET: "XXXXXXXXXXXXXXXXXXTEST=="
  APP_KEYS: "XXXXXXXXXXXXXXXXXXTEST==,XXXXXXXXXXXXXXXXXXTEST==,XXXXXXXXXXXXXXXXXXTEST==,XXXXXXXXXXXXXXXXXXTEST=="
  API_TOKEN_SALT: "XXXXXXXXXXXXXXTEST=="
  ADMIN_JWT_SECRET: "XXXXXXXXXXXTEST=="
  CF_ENDPOINT: "83bfc104d4a2e71a5d8210f2364ee9e4.r2.cloudflarestorage.com"
  CF_BUCKET: "andycinquin"
  CF_PUBLIC_ACCESS_URL: "r2-andycinquin.andy-cinquin.fr"
  CF_ACCESS_SECRET: ""
  CF_ACCESS_KEY_ID: ""
  DEEPL_API_KEY: ""
  DEEPL_API_URL: ""

jobs:
  just-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use and cache Node 20.x Yarn
        uses: actions/setup-node@v6
        with:
          cache: 'yarn'
          node-version: 20.x
      - name: Yarn install and build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Try Building image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ secrets.APP_IMAGE }}